In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import datetime as dt
import os
import io

In [2]:
# Data loading
data0 = pd.read_csv("a.us.txt")
data1 = pd.read_csv("aa.us.txt")
data2 = pd.read_csv("aaap.us.txt")
data3 = pd.read_csv("aaba.us.txt")
data4 = pd.read_csv("aac.us.txt")
data5 = pd.read_csv("aal.us.txt")
data6 = pd.read_csv("aamc.us.txt")
data7 = pd.read_csv("aame.us.txt")
data8 = pd.read_csv("aan.us.txt")
data9 = pd.read_csv("aaoi.us.txt")
# Data joining
df = [data0, data1, data2, data3, data4, data5, data6, data7, data8, data9]
key = ['a', 'aa', 'aaap', 'aaba', 'aac', 'aal', 'aamc', 'aame', 'aan', 'aaoi']

In [3]:
name = ['Stock_Name', 'ID']
final = pd.concat(df, keys = key, names = name)
display(final)

                       Date    Open     High      Low   Close    Volume  \
Stock_Name ID
a          0     1999-11-18  30.713  33.7540  27.0020  29.702  66277506
           1     1999-11-19  28.986  29.0270  26.8720  27.257  16142920
           2     1999-11-22  27.886  29.7020  27.0440  29.702   6970266
           3     1999-11-23  28.688  29.4460  27.0020  27.002   6332082
           4     1999-11-24  27.083  28.3090  27.0020  27.717   5132147
...                     ...     ...      ...      ...     ...       ...
aaoi       1036  2017-11-06  37.580  38.7200  36.7000  37.800   2388819
           1037  2017-11-07  37.980  38.0750  36.9700  37.890   3408164
           1038  2017-11-08  40.470  44.6432  39.1000  43.640   7669971
           1039  2017-11-09  43.000  44.2400  41.3441  43.200   2867311
           1040  2017-11-10  42.670  46.0717  42.5500  45.300   2967517

                 OpenInt
Stock_Name ID
a          0           0
           1           0
           2           0
           3           0
           4           0
...                  ...
aaoi       1036        0
           1037        0
           1038        0
           1039        0
           1040        0

[32687 rows x 7 columns]

In [4]:
del final['OpenInt']
final.head()

                     Date    Open    High     Low   Close    Volume
Stock_Name ID
a          0   1999-11-18  30.713  33.754  27.002  29.702  66277506
           1   1999-11-19  28.986  29.027  26.872  27.257  16142920
           2   1999-11-22  27.886  29.702  27.044  29.702   6970266
           3   1999-11-23  28.688  29.446  27.002  27.002   6332082
           4   1999-11-24  27.083  28.309  27.002  27.717   5132147

In [5]:
# There is no mode for this dataframe, therefore all numbers are unique values 
# Calculates the mean for all columns except for date
final.groupby(level=['Stock_Name'])[['Open', 'High', 'Low', 'Close', 'Volume']].mean()

                  Open        High         Low       Close        Volume
Stock_Name
a            27.856296   28.270442   27.452486   27.871357  3.993503e+06
aa           24.419762   24.751516   24.056557   24.406203  3.337757e+06
aaap         37.229466   38.032705   36.466674   37.342337  1.499889e+05
aaba         25.401708   25.862379   24.925755   25.388213  2.321796e+07
aac          19.510399   20.065225   18.933637   19.478599  2.204412e+05
aal          41.150250   41.751690   40.537996   41.150520  1.004541e+07
aamc        275.232759  283.057715  267.766011  276.034721  1.764443e+04
aame          2.799858    2.854107    2.740064    2.807845  6.715761e+03
aan          23.178208   23.497556   22.851696   23.182218  7.139724e+05
aaoi         24.617401   25.289652   23.931701   24.626871  7.940869e+05

In [6]:
# Calculates the median for all columns except for date
final.groupby(level=['Stock_Name'])[['Open', 'High', 'Low', 'Close', 'Volume']].median()

                Open      High       Low     Close      Volume
Stock_Name
a            24.4560   24.8090   24.1590   24.4900   3460621.0
aa           16.4530   16.6620   16.2430   16.4740   1395957.5
aaap         35.1100   35.9900   34.3500   35.2500     56000.0
aaba         23.3750   23.7250   23.0000   23.4400  18309490.0
aac          19.6000   20.0500   19.0000   19.5500    143945.0
aal          41.2410   41.7410   40.5940   41.2310   8685476.0
aamc        125.0000  128.0000  123.2500  125.5000     10331.0
aame          2.8873    2.8973    2.8405    2.8873      3471.0
aan          22.9470   23.4190   22.5830   22.9920    563514.0
aaoi         18.3700   18.7900   17.8600   18.3100    278082.0

In [7]:
# Calculates the standard deviation for all columns except for date
final.groupby(level=['Stock_Name'])[['Open', 'High', 'Low', 'Close', 'Volume']].std()

                  Open        High         Low       Close        Volume
Stock_Name
a            12.940880   13.176000   12.711735   12.944389  2.665730e+06
aa           23.647989   23.990163   23.260402   23.627596  5.203407e+06
aaap         11.431735   11.571366   11.403332   11.494574  5.411410e+05
aaba         17.241659   17.642258   16.848659   17.235488  2.127747e+07
aac           9.945027   10.194789    9.670007    9.928995  3.877946e+05
aal           6.344948    6.346726    6.284963    6.304682  6.971825e+06
aamc        320.461481  328.602211  312.187507  321.108278  2.406703e+04
aame          1.076077    1.083340    1.062140    1.074637  1.239398e+04
aan           7.237382    7.289445    7.186433    7.237218  6.354874e+05
aaoi         17.848195   18.422152   17.290748   17.871792  1.426773e+06

In [8]:
# Check for duplicated values
print(final.duplicated().any())

False

In [9]:
# Check for null values
print(final.isnull().any())

Date      False
Open      False
High      False
Low       False
Close     False
Volume    False
dtype: bool